// Queue approval decisions travel exclusively through standard AG-UI resume.
import {readFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';
const require=createRequire(new URL('../../../agently-core-ag-ui/sdk/ts/package.json',import.meta.url));const {HttpAgent}=require('@ag-ui/client');const {EventSchema}=require('@ag-ui/core/schemas');
const url=process.env.AGENTLY_AGUI_URL??'http://127.0.0.1:18193/v1/ag-ui/run';for(let attempt=0;attempt<30;attempt++){try{if((await fetch(new URL('/healthz',url))).ok)break}catch{}if(attempt===29)throw new Error('Assembly backend did not become ready');await new Promise(r=>setTimeout(r,500));}
const effectLog=process.env.AGENTLY_AGUI_APPROVAL_EFFECT_LOG;
const effectCount=async()=>{try{return(await readFile(effectLog,'utf8')).split('\n').filter(Boolean).length}catch(e){if(e.code==='ENOENT')return 0;throw e}};
if(effectLog)assert.equal(await effectCount(),0,'effect log must be new');
let cookie='';const wires=[];const requests=[];let count=0;
const transport=async(input,init)=>{requests.push(JSON.parse(init.body));const r=await fetch(input,{...init,headers:{...init.headers,...(cookie?{cookie}:{})}});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];if(!r.ok)throw new Error(`HTTP ${r.status}: ${await r.text()}`);wires.push(r.clone().text());return r};
for(const action of ['approve','reject']){
 const agent=new HttpAgent({url,fetch:transport,threadId:randomUUID(),initialMessages:[{id:randomUUID(),role:'user',content:effectLog?'fixture-tool-approval-effect please':'fixture-tool approval please'}]});const forwardedProps={agently:{version:'1',operation:'chat',payload:{agentId:effectLog?'approval_effect_fixture':'approval_fixture',model:'local_mock'}}};let outcome;let failure;
 await agent.runAgent({runId:randomUUID(),forwardedProps},{onRunFinishedEvent:({event})=>{outcome=event.outcome},onRunErrorEvent:({event})=>{failure=event.message}});assert.equal(failure,undefined);assert.equal(outcome.type,'interrupt');assert.equal(outcome.interrupts.length,1);const interrupt=outcome.interrupts[0];assert.equal(interrupt.reason,'approval');assert.match(interrupt.toolCallId,/^agui\.tool\/[^/]+\/fixture-tool-call$/);
 const original=agent.messages.flatMap(m=>m.toolCalls??[]).find(c=>c.id===interrupt.toolCallId);assert.ok(original);if(!effectLog)assert.deepEqual(JSON.parse(original.function.arguments),{names:['AGENTLY_AGUI_FIXTURE_VALUE']});else assert.equal(await effectCount(),action==='approve'?0:1,'no effect before approval decision');assert.equal(agent.messages.filter(m=>m.role==='tool'&&m.toolCallId===original.id).length,0,'approval must not fabricate a result before decision');
 failure=undefined;await agent.runAgent({runId:randomUUID(),forwardedProps,resume:[{interruptId:interrupt.id,status:'resolved',payload:{action}}]},{onRunFinishedEvent:({event})=>{outcome=event.outcome},onRunErrorEvent:({event})=>{failure=event.message}});assert.equal(failure,undefined);assert.equal(outcome.type,'success');assert.equal(agent.messages.flatMap(m=>m.toolCalls??[]).filter(c=>c.id===original.id).length,1);const results=agent.messages.filter(m=>m.role==='tool'&&m.toolCallId===original.id);assert.equal(results.length,1,'decision must complete the original tool call once');if(effectLog){if(action==='approve')assert.ok(results[0].content.includes('fixture-effect-recorded'),'actual command result must be routed to original call');assert.equal(await effectCount(),1,action==='approve'?'approved tool executes once':'rejected tool executes zero times');const replay=await fetch(url,{method:'POST',headers:{'content-type':'application/json',cookie},body:JSON.stringify(requests.at(-1))});assert.equal(replay.status,200);assert.equal(await replay.text(),await wires.at(-1));assert.equal(await effectCount(),1,'replay must not execute an approved tool again');}else if(action==='approve')assert.ok(results[0].content.includes('fixture-value'));else assert.ok(!results[0].content.includes('fixture-value'),'rejected tool must not execute');assert.ok(agent.messages.some(m=>m.role==='assistant'&&m.content==='Hello from the local Agently AG-UI assembly fixture.'));console.log(`approval ${action}: original scoped call completed once via standard resume`);
}
for(const wire of await Promise.all(wires))for(const frame of wire.split(/\r?\n\r?\n/)){const data=frame.split(/\r?\n/).filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(data){EventSchema.parse(JSON.parse(data));count++}}
console.log(`Approval smoke passed; ${count} official-schema wire events`);
