package agent

import (
	"github.com/tmc/langchaingo/schema"
	agentmdl "github.com/viant/agently/genai/agent"
	"github.com/viant/agently/genai/agent/plan"
	"github.com/viant/agently/genai/usage"
)

// QueryInput represents the input for querying an agent's knowledge
type QueryInput struct {
	// ConversationID is an optional identifier for the conversation session.
	// If provided, conversation history will be tracked and reused.
	ConversationID string `json:"conversationId,omitempty"`
	// Optional client-supplied identifier for the user message. When empty the
	// service will generate a UUID.
	MessageID       string          `json:"messageId,omitempty"`
	AgentName       string          `json:"agentName"`       // Path to the agent configuration
	Agent           *agentmdl.Agent `json:"agent"`           // Agent to use (alternative to AgentName)
	Query           string          `json:"query"`           // The query to submit
	MaxResponseSize int             `json:"maxResponseSize"` // Maximum size of the response in bytes
	MaxDocuments    int             `json:"maxDocuments"`    // Maximum number of documents to retrieve
	IncludeFile     bool            `json:"includeFile"`     // Whether to include complete file content
	EmbeddingModel  string          `json:"embeddingModel"`  // Find to use for embeddings

	// Optional runtime overrides (single-turn)
	ModelOverride string                 `json:"model,omitempty"` // llm model name
	ToolsAllowed  []string               `json:"tools,omitempty"` // allow-list for tools (empty = default)
	Context       map[string]interface{} `json:"context,omitempty"`

	// ElicitationMode controls how missing-input requests are handled.
	//   "user"   – always forward to end-user (current default)
	//   "agent"  – auto-fill using sub-agent; fail when unable
	//   "hybrid" – try agent first; fall back to real user when needed.
	ElicitationMode string `json:"elicitationMode,omitempty" yaml:"elicitationMode,omitempty"`

	// Persona overrides the default role/actor for the messages generated by
	// this query. When nil, the agent's configured persona (if any) is used.
	Persona *agentmdl.Persona `json:"persona,omitempty" yaml:"persona,omitempty"`
}

// QueryOutput represents the result of an agent knowledge query
type QueryOutput struct {
	Agent         *agentmdl.Agent   `json:"agent"`                 // Agent used for the query
	Content       string            `json:"content"`               // Generated content from the agent
	Documents     []schema.Document `json:"documents"`             // List of relevant documents
	DocumentsSize int               `json:"documentsSize"`         // Total size of retrieved documents
	Elicitation   *plan.Elicitation `json:"elicitation,omitempty"` // structured missing input request
	Plan          *plan.Plan        `json:"plan,omitempty"`        // current execution plan (optional)
	Usage         *usage.Aggregator `json:"usage,omitempty"`
	Model         string            `json:"model,omitempty"`
}
