package read

import (
	"context"
	"embed"
	"fmt"
	"github.com/viant/datly"
	"github.com/viant/datly/repository"
	"github.com/viant/datly/repository/contract"
	"github.com/viant/datly/view"
	"github.com/viant/xdatly/handler/response"
	"github.com/viant/xdatly/types/core"
	"github.com/viant/xdatly/types/custom/dependency/checksum"
	"reflect"
	"time"
)

// Code generated by datly. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

func init() {
	core.RegisterType("read", "GeneratedFileInput", reflect.TypeOf(GeneratedFileInput{}), checksum.GeneratedTime)
	core.RegisterType("read", "GeneratedFileOutput", reflect.TypeOf(GeneratedFileOutput{}), checksum.GeneratedTime)
}

//go:embed generated_file/*.sql
var GeneratedFileFS embed.FS

type GeneratedFileInput struct {
	ConversationID string                 `parameter:",kind=query,in=conversationId" predicate:"equal,group=0,t,conversation_id"`
	TurnID         string                 `parameter:",kind=query,in=turnId" predicate:"equal,group=0,t,turn_id"`
	MessageID      string                 `parameter:",kind=query,in=messageId" predicate:"equal,group=0,t,message_id"`
	ID             string                 `parameter:",kind=query,in=id" predicate:"equal,group=0,t,id"`
	Provider       string                 `parameter:",kind=query,in=provider" predicate:"equal,group=0,t,provider"`
	Status         string                 `parameter:",kind=query,in=status" predicate:"equal,group=0,t,status"`
	Since          time.Time              `parameter:",kind=query,in=since" predicate:"greater_or_equal,group=0,t,created_at"`
	Has            *GeneratedFileInputHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-"`
}

type GeneratedFileInputHas struct {
	ConversationID bool
	TurnID         bool
	MessageID      bool
	ID             bool
	Provider       bool
	Status         bool
	Since          bool
}

type GeneratedFileOutput struct {
	ResponseStatus response.Status      `parameter:",kind=output,in=status" json:",omitempty"`
	Data           []*GeneratedFileView `parameter:",kind=output,in=view" view:"generated_file,batch=10000,relationalConcurrency=1" sql:"uri=generated_file/generated_file.sql"`
	Metrics        response.Metrics     `parameter:",kind=output,in=metrics"`
}

type GeneratedFileView struct {
	Id             string     `sqlx:"id"`
	ConversationId string     `sqlx:"conversation_id"`
	TurnId         *string    `sqlx:"turn_id"`
	MessageId      *string    `sqlx:"message_id"`
	Provider       string     `sqlx:"provider"`
	Mode           string     `sqlx:"mode"`
	CopyMode       string     `sqlx:"copy_mode"`
	Status         string     `sqlx:"status"`
	PayloadId      *string    `sqlx:"payload_id"`
	ContainerId    *string    `sqlx:"container_id"`
	ProviderFileId *string    `sqlx:"provider_file_id"`
	Filename       *string    `sqlx:"filename"`
	MimeType       *string    `sqlx:"mime_type"`
	SizeBytes      *int       `sqlx:"size_bytes"`
	Checksum       *string    `sqlx:"checksum"`
	ErrorMessage   *string    `sqlx:"error_message"`
	ExpiresAt      *time.Time `sqlx:"expires_at"`
	CreatedAt      time.Time  `sqlx:"created_at"`
	UpdatedAt      *time.Time `sqlx:"updated_at"`
}

var GeneratedFilePathURI = "/v1/api/agently/generatedfile/read"

func DefineGeneratedFileComponent(ctx context.Context, srv *datly.Service) error {
	aComponent, err := repository.NewComponent(
		contract.NewPath("GET", GeneratedFilePathURI),
		repository.WithResource(srv.Resource()),
		repository.WithContract(
			reflect.TypeOf(GeneratedFileInput{}),
			reflect.TypeOf(GeneratedFileOutput{}), &GeneratedFileFS, view.WithConnectorRef("agently")))

	if err != nil {
		return fmt.Errorf("failed to create GeneratedFile component: %w", err)
	}
	if err := srv.AddComponent(ctx, aComponent); err != nil {
		return fmt.Errorf("failed to add GeneratedFile component: %w", err)
	}
	return nil
}

func (i *GeneratedFileInput) EmbedFS() *embed.FS {
	return &GeneratedFileFS
}
