package schedule

import (
	"context"
	"embed"
	"fmt"
	"github.com/viant/datly"
	"github.com/viant/datly/repository"
	"github.com/viant/datly/repository/contract"
	"github.com/viant/datly/view"
	"github.com/viant/xdatly/handler/response"
	"github.com/viant/xdatly/types/core"
	"github.com/viant/xdatly/types/custom/dependency/checksum"
	"reflect"
	"time"
)

// Code generated by datly. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

func init() {
	core.RegisterType("schedule", "ScheduleInput", reflect.TypeOf(ScheduleInput{}), checksum.GeneratedTime)
	core.RegisterType("schedule", "ScheduleOutput", reflect.TypeOf(ScheduleOutput{}), checksum.GeneratedTime)
}

//go:embed schedule/*.sql
var ScheduleFS embed.FS

type ScheduleInput struct {
	Id  string            `parameter:",kind=path,in=id" predicate:"equal,group=0,t,id"`
	Has *ScheduleInputHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-"`
}

type ScheduleInputHas struct {
	Id bool
}

type ScheduleOutput struct {
	response.Status `parameter:",kind=output,in=status" json:",omitempty"`
	Data            []*ScheduleView  `parameter:",kind=output,in=view" view:"schedule,batch=10000,relationalConcurrency=1" sql:"uri=schedule/schedule.sql"`
	Metrics         response.Metrics `parameter:",kind=output,in=metrics"`
}

type ScheduleView struct {
	Id              string     `sqlx:"id"`
	Name            string     `sqlx:"name"`
	Description     *string    `sqlx:"description"`
	AgentRef        string     `sqlx:"agent_ref"`
	ModelOverride   *string    `sqlx:"model_override"`
	Enabled         bool       `sqlx:"enabled"`
	StartAt         *time.Time `sqlx:"start_at"`
	EndAt           *time.Time `sqlx:"end_at"`
	ScheduleType    string     `sqlx:"schedule_type"`
	CronExpr        *string    `sqlx:"cron_expr"`
	IntervalSeconds *int       `sqlx:"interval_seconds"`
	Timezone        string     `sqlx:"timezone"`
	TaskPromptUri   *string    `sqlx:"task_prompt_uri"`
	TaskPrompt      *string    `sqlx:"task_prompt"`
	NextRunAt       *time.Time `sqlx:"next_run_at"`
	LastRunAt       *time.Time `sqlx:"last_run_at"`
	LastStatus      *string    `sqlx:"last_status"`
	LastError       *string    `sqlx:"last_error"`
	LeaseOwner      *string    `sqlx:"lease_owner"`
	LeaseUntil      *time.Time `sqlx:"lease_until"`
	CreatedAt       time.Time  `sqlx:"created_at"`
	UpdatedAt       *time.Time `sqlx:"updated_at"`
}

var SchedulePathURI = "/v1/api/agently/scheduler/schedule/{id}"

func DefineScheduleComponent(ctx context.Context, srv *datly.Service) error {
	aComponent, err := repository.NewComponent(
		contract.NewPath("GET", SchedulePathURI),
		repository.WithResource(srv.Resource()),
		repository.WithContract(
			reflect.TypeOf(ScheduleInput{}),
			reflect.TypeOf(ScheduleOutput{}), &ScheduleFS, view.WithConnectorRef("agently")))

	if err != nil {
		return fmt.Errorf("failed to create Schedule component: %w", err)
	}
	if err := srv.AddComponent(ctx, aComponent); err != nil {
		return fmt.Errorf("failed to add Schedule component: %w", err)
	}
	return nil
}

func (i *ScheduleInput) EmbedFS() *embed.FS {
	return &ScheduleFS
}
