pipeline:
  translate:
    action: exec:run
    TimeoutMs: 120000
    checkError: true
    commands:
      - cd $repoPath
      - $repoPath/bin/datly gen -o=get -u=agently/conversation      -s='dql/agently/conversation/conversation.dql' $datlyOptions

