package com.viant.agently.android

import com.viant.agentlysdk.GeneratedFileEntry
import com.viant.agentlysdk.PendingToolApproval
import kotlinx.serialization.json.JsonElement

internal data class AppUiCallbacks(
    val onRefreshWorkspace: () -> Unit,
    val onNewConversation: () -> Unit,
    val onSelectAgent: (String?) -> Unit,
    val onOpenHistory: () -> Unit,
    val onOpenSettings: () -> Unit,
    val onSelectConversation: (String) -> Unit,
    val onApprovalEditChange: (String, String, JsonElement) -> Unit,
    val onApprovalDecision: (PendingToolApproval, String) -> Unit,
    val onOpenFile: (GeneratedFileEntry) -> Unit,
    val onOpenInlineReportPdf: (Map<String, Any?>) -> Unit,
    val onClosePreview: () -> Unit,
    val onQueryChange: (String) -> Unit,
    val onComposerLookupSelected: (ComposerLookupOccurrence) -> Unit,
    val onStarterTaskSelected: (String) -> Unit,
    val onRunQuery: () -> Unit,
    val onBackFromHistory: () -> Unit,
    val onBackFromSettings: () -> Unit,
    val onRefreshAuth: () -> Unit,
    val onSaveSettings: (String, String, SavedLoginConfig) -> Unit,
    val onResetAppOverrides: () -> Unit,
    val onClearAuthSecrets: () -> Unit,
    val onAuthSignIn: () -> Unit,
    val onAuthOobSignIn: () -> Unit,
    val onDeveloperSessionSignIn: (String) -> Unit,
    val onAuthRetry: () -> Unit,
    val onDismissAuthWeb: () -> Unit,
    val onOAuthCallback: (String, String) -> Unit
)

internal fun buildAppUiCallbacks(
    currentScreenProvider: () -> AppScreen,
    setCurrentScreen: (AppScreen) -> Unit,
    onRefreshWorkspace: () -> Unit,
    onNewConversation: () -> Unit,
    onSelectAgent: (String?) -> Unit,
    onSelectConversation: (String, Boolean) -> Unit,
    onApprovalEditChange: (String, String, JsonElement) -> Unit,
    onApprovalDecision: (PendingToolApproval, String) -> Unit,
    onOpenFile: (GeneratedFileEntry) -> Unit,
    onOpenInlineReportPdf: (Map<String, Any?>) -> Unit,
    onClosePreview: () -> Unit,
    onQueryChange: (String) -> Unit,
    onComposerLookupSelected: (ComposerLookupOccurrence) -> Unit,
    onStarterTaskSelected: (String) -> Unit,
    onRunQuery: () -> Unit,
    onRefreshAuth: () -> Unit,
    onSaveSettings: (String, String, SavedLoginConfig) -> Unit,
    onResetAppOverrides: () -> Unit,
    onClearAuthSecrets: () -> Unit,
    onAuthSignIn: () -> Unit,
    onAuthOobSignIn: () -> Unit,
    onDeveloperSessionSignIn: (String) -> Unit,
    onAuthRetry: () -> Unit,
    onDismissAuthWeb: () -> Unit,
    onOAuthCallback: (String, String) -> Unit
): AppUiCallbacks = AppUiCallbacks(
    onRefreshWorkspace = onRefreshWorkspace,
    onNewConversation = onNewConversation,
    onSelectAgent = onSelectAgent,
    onOpenHistory = { setCurrentScreen(AppScreen.History) },
    onOpenSettings = { setCurrentScreen(AppScreen.Settings) },
    onSelectConversation = {
        onSelectConversation(it, currentScreenProvider() == AppScreen.History)
    },
    onApprovalEditChange = onApprovalEditChange,
    onApprovalDecision = onApprovalDecision,
    onOpenFile = onOpenFile,
    onOpenInlineReportPdf = onOpenInlineReportPdf,
    onClosePreview = onClosePreview,
    onQueryChange = onQueryChange,
    onComposerLookupSelected = onComposerLookupSelected,
    onStarterTaskSelected = onStarterTaskSelected,
    onRunQuery = onRunQuery,
    onBackFromHistory = { setCurrentScreen(AppScreen.Chat) },
    onBackFromSettings = { setCurrentScreen(AppScreen.Chat) },
    onRefreshAuth = onRefreshAuth,
    onSaveSettings = onSaveSettings,
    onResetAppOverrides = onResetAppOverrides,
    onClearAuthSecrets = onClearAuthSecrets,
    onAuthSignIn = onAuthSignIn,
    onAuthOobSignIn = onAuthOobSignIn,
    onDeveloperSessionSignIn = onDeveloperSessionSignIn,
    onAuthRetry = onAuthRetry,
    onDismissAuthWeb = onDismissAuthWeb,
    onOAuthCallback = onOAuthCallback
)
